my_snake:
  name: <%= ENV['NAME'] %>
  st_method: <%= ENV['ST_METHOD'] %>
  color: <%= ENV['COLOR'] %>
  head_type: <%= ENV['HEAD_TYPE'] %>
  head_url: <%= ENV['HEAD_URL'] %>
  tail_type: <%= ENV['TAIL_TYPE'] %>
grid:
  enemy_head: "▓"
  enemy_body: "█"
  me_head: "▒"
  me_body: "█"
  food: "♥"
wall:
  degree: <%= ENV['WALL_DEGREE'] %>
  weight: <%= ENV['WALL_WEIGHT'] %> 
tree:
  levels: <%= ENV['TREE_LEVELS'] %>
  min_threshold: <%= ENV['TREE_MIN_THRESHOLD'] %>
  threshold: <%= ENV['TREE_THRESHOLD'] %>
snake:
  me:
    body:
      degree: <%= ENV['SNAKE_MY_BODY_DEGREE'] %>
      weight: <%= ENV['SNAKE_MY_BODY_WEIGHT'] %>
    head:
      degree: <%= ENV['SNAKE_MY_HEAD_DEGREE'] %>
      weight: <%= ENV['SNAKE_MY_HEAD_WEIGHT'] %>
  enemy:
    body:
      degree: <%= ENV['SNAKE_ENEMY_BODY_DEGREE'] %>
      weight: <%= ENV['SNAKE_ENEMY_BODY_WEIGHT'] %>
    head:
      degree: <%= ENV['SNAKE_ENEMY_HEAD_DEGREE'] %>
      weight: <%= ENV['SNAKE_ENEMY_HEAD_WEIGHT'] %>
    length_weight: <%= ENV['SNAKE_ENEMY_LENGTH_WEIGHT'] %>
food: 
  mult: <%= ENV['FOOD_MULT'] %>
  weight: <%= ENV['FOOD_WEIGHT'] %>
  degree: <%= ENV['FOOD_DEGREE'] %>
